# Generated by Django 5.0.4 on 2024-05-04 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorystay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sitter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('S_name', models.CharField(blank=True, max_length=200, null=True)),
                ('Gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('dob', models.DateTimeField(auto_now_add=True)),
                ('location', models.CharField(default='Kabalaga', max_length=200)),
                ('next_of_kin', models.CharField(max_length=200)),
                ('recommenders_name', models.CharField(max_length=200)),
                ('religion', models.CharField(blank=True, choices=[('Christian', 'Christian'), ('Muslim', 'Muslim'), ('Other', 'Other')], max_length=100)),
                ('NIN', models.CharField(max_length=30, unique=True)),
                ('education_level', models.CharField(choices=[('Primary', 'Primary'), ('Secondary', 'Secondary'), ('University', 'University')], max_length=200)),
                ('sitter_number', models.CharField(max_length=200, unique=True)),
                ('contact', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Baby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('B_name', models.CharField(blank=True, max_length=200, null=True)),
                ('Gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('age', models.IntegerField(blank=True, default=0, null=True)),
                ('fathers_name', models.CharField(blank=True, max_length=255, null=True)),
                ('mothers_name', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(max_length=255)),
                ('mothers_phone', models.IntegerField(null=True)),
                ('fathers_phone', models.IntegerField(null=True)),
                ('brought_by', models.CharField(blank=True, max_length=200, null=True)),
                ('timeIn', models.DateTimeField(blank=True, null=True)),
                ('timeOut', models.DateTimeField(blank=True, null=True)),
                ('baby_number', models.PositiveIntegerField()),
                ('c_stay', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DaystarApp.categorystay')),
                ('assign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DaystarApp.sitter')),
            ],
        ),
    ]
