# Generated by Django 5.0.4 on 2024-05-08 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DaystarApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitter',
            name='dob',
        ),
    ]
