# Generated by Django 5.0.4 on 2024-05-08 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DaystarApp', '0002_remove_sitter_dob'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0, help_text='Amount in Ugandan Shillings (UGX)')),
                ('payment_type', models.CharField(choices=[('half_day', 'Half Day Payment (10,000 UGX)'), ('full_day', 'Full Day Payment (15,000 UGX)')], max_length=10)),
                ('date_of_payment', models.DateTimeField(blank=True, null=True)),
                ('S_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DaystarApp.sitter')),
            ],
        ),
    ]
